{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "httpbin.fullname" . }}-egress
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "httpbin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.networkPolicy.defaultDenyEgress }}
    []  # default deny; add explicit allows below
    {{- end }}
{{- if .Values.networkPolicy.allowDNS }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "httpbin.fullname" . }}-egress-dns
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "httpbin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
{{- if gt (len .Values.networkPolicy.additionalEgressRules) 0 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "httpbin.fullname" . }}-egress-extra
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "httpbin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    {{- toYaml .Values.networkPolicy.additionalEgressRules | nindent 4 }}
{{- end }}
{{- end }}
