{{- if and .Values.rollout.enabled (not .Values.useDeploymentFallback) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.canaryServiceName }}
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "httpbin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
