apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.enabled | ternary .Values.rollout.stableServiceName (include "httpbin.fullname" .) }}
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "httpbin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
