name: Chart Testing

on:
  pull_request:
    branches: [ "**" ]

jobs:
  ct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --config .ct.yaml --charts deployments/httpbin --validate-maintainers=false

      - name: Run chart-testing (install)
        run: ct install --config .ct.yaml --charts deployments/httpbin


