# Example environment-specific overrides

image:
  repository: kennethreitz/httpbin
  tag: "latest"
  pullPolicy: Always ## This is not recommended for production, but it is allowed for dev.

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
